# 项目名
server:
  servlet:
    context-path: /mulDataSourceApi
    application-display-name: mulDataSourceApi
# spring配置
spring:
  profiles:
    active: dev
  main:
    banner-mode: console
  output:
    ansi:
      enabled: detect
# http配置，编码格式utf-8 HttpMessageConverter换为 Gson 速度稍慢但是稳定
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
    converters:
      preferred-json-mapper: gson
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  freemarker:
    cache: false
    charset: UTF-8
    request-context-attribute: request
# logging config
logging:
  register-shutdown-hook: true